name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Run ESLint
      run: yarn lint:check
  docs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Check Docs
      run: yarn docs:check
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run Tests
      run: yarn test
